package vista;

import controlador.ControladorLogin;
import modelo.Validaciones;



/**
 *
 * @author oriana
 */
public class Login1 extends javax.swing.JFrame {

Validaciones val = new Validaciones();

    public Login1() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSEffectFade1 = new rojeru_san.complementos.RSEffectFade();
        rSScaleLabel1 = new rsscalelabel.RSScaleLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPass = new rojeru_san.rsfield.RSPassViewBD();
        txtUsuario = new rojeru_san.rsfield.RSTextFullBD();
        btnIniciar = new rojeru_san.rsbutton.RSButtonRoundRipple();
        rSPanelGradiente1 = new rojeru_san.rspanel.RSPanelGradiente();
        btnCerrar = new RSMaterialComponent.RSButtonIconUno();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(131, 202, 205));

        txtPass.setForeground(new java.awt.Color(97, 180, 184));
        txtPass.setBordeColorFocus(new java.awt.Color(97, 180, 184));
        txtPass.setBotonColor(new java.awt.Color(97, 180, 184));
        txtPass.setPlaceholder("Ingresar contraseña");
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });

        txtUsuario.setForeground(new java.awt.Color(97, 180, 184));
        txtUsuario.setBordeColorFocus(new java.awt.Color(97, 180, 184));
        txtUsuario.setBotonColor(new java.awt.Color(97, 180, 184));
        txtUsuario.setPlaceholder("Ingresar usuario");
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        btnIniciar.setBackground(new java.awt.Color(15, 158, 168));
        btnIniciar.setText("Iniciar Sesión");
        btnIniciar.setColorHover(new java.awt.Color(97, 180, 184));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(15, 158, 168));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(131, 202, 205));

        btnCerrar.setBackground(new java.awt.Color(131, 202, 205));
        btnCerrar.setBackgroundHover(new java.awt.Color(131, 202, 205));
        btnCerrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
      /* UsuarioDao dao = new UsuarioDao();
       Usuario mod = new Usuario();
       
       String pass =new String(txtPass.getPassword());
       
        if (!txtUsuario.getText().equals("") && !pass.equals("")) 
        {//el hash lo que hace es encriptar las contraseñas
               //String nuevoPass= hash.sha1(pass);
               mod.setUsuario(txtUsuario.getText());
               mod.setContrasenna(pass);
               if (dao.login(mod)) {
                this.dispose();
                VentanaPrin prin = new VentanaPrin(mod);
                prin.setVisible(true);
            }else
               {
                   JOptionPane.showMessageDialog(null, "Datos incorrectos");
               }
        }else
        {//datos vacios
            JOptionPane.showMessageDialog(null, "Ingresar datos");
        }*/
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        val.restringircaracteres(evt);
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        
    }//GEN-LAST:event_txtPassKeyPressed

    public void addEvents(java.awt.event.ActionListener evt)
    {
    btnIniciar.addActionListener(evt);
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       ControladorLogin cl = new ControladorLogin();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconUno btnCerrar;
    public rojeru_san.rsbutton.RSButtonRoundRipple btnIniciar;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.complementos.RSEffectFade rSEffectFade1;
    private rojeru_san.rspanel.RSPanelGradiente rSPanelGradiente1;
    private rsscalelabel.RSScaleLabel rSScaleLabel1;
    public rojeru_san.rsfield.RSPassViewBD txtPass;
    public rojeru_san.rsfield.RSTextFullBD txtUsuario;
    // End of variables declaration//GEN-END:variables
}
