package vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oriana
 */
public class MenuReporte extends javax.swing.JFrame {

    public MenuReporte() {
          initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }
public void addEvents(java.awt.event.ActionListener evt){
    btnDetalleEntr.addActionListener(evt);
    btnCerrarSesion.addActionListener(evt);
    btnDetallePeli.addActionListener(evt);
    btnAtras.addActionListener(evt);
   
    jMenuItem1LCF.addActionListener(evt);
    jMenuItem2LRE.addActionListener(evt);
    jMenuItem3LP.addActionListener(evt);
    jMenuItem5LEG.addActionListener(evt);
    jMenuItem6MGC.addActionListener(evt);
    jMenuItem7LPP.addActionListener(evt);
    
   // String mensaje = jListaReportes.getSelectedValue().toString();
   // int indice= jListaReportes.getSelectedIndex();
    
    //la salida seria algo.setText(mensaje) y me devuelve lo que
    //esta en la lista
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelGradiente1 = new rojeru_san.rspanel.RSPanelGradiente();
        btnDetallePeli = new rojeru_san.rsbutton.RSButtonForma();
        jLabel2 = new javax.swing.JLabel();
        btnDetalleEntr = new rojeru_san.rsbutton.RSButtonForma();
        btnCerrarSesion = new rojeru_san.rsbutton.RSButtonForma();
        btnAtras = new rojeru_san.rsbutton.RSButtonForma();
        rSMenuBar1 = new rojerusan.RSMenuBar();
        btnMenu = new javax.swing.JMenu();
        jMenuItem1LCF = new javax.swing.JMenuItem();
        jMenuItem2LRE = new javax.swing.JMenuItem();
        jMenuItem3LP = new javax.swing.JMenuItem();
        jMenuItemIO = new javax.swing.JMenuItem();
        jMenuItem5LEG = new javax.swing.JMenuItem();
        jMenuItem6MGC = new javax.swing.JMenuItem();
        jMenuItem7LPP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(131, 202, 205));

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(131, 202, 205));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(15, 158, 168));

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        btnDetallePeli.setBackground(new java.awt.Color(15, 158, 168));
        btnDetallePeli.setText("Detalle Película");
        btnDetallePeli.setColorHover(new java.awt.Color(97, 180, 184));
        btnDetallePeli.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(131, 202, 205));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menú de Opciones");

        btnDetalleEntr.setBackground(new java.awt.Color(15, 158, 168));
        btnDetalleEntr.setText("Detalle Entradas");
        btnDetalleEntr.setColorHover(new java.awt.Color(97, 180, 184));
        btnDetalleEntr.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N

        btnCerrarSesion.setBackground(new java.awt.Color(15, 158, 168));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setColorHover(new java.awt.Color(97, 180, 184));
        btnCerrarSesion.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N

        btnAtras.setBackground(new java.awt.Color(15, 158, 168));
        btnAtras.setText("Atrás");
        btnAtras.setColorHover(new java.awt.Color(97, 180, 184));
        btnAtras.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDetallePeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDetalleEntr, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel2)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetallePeli, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalleEntr, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        rSMenuBar1.setBackground(new java.awt.Color(131, 202, 205));

        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Menú de Reportes");
        btnMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem1LCF.setText("Listado de Clientes Frecuentes");
        jMenuItem1LCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1LCFActionPerformed(evt);
            }
        });
        btnMenu.add(jMenuItem1LCF);

        jMenuItem2LRE.setText("Listado de Resumen Edades");
        btnMenu.add(jMenuItem2LRE);

        jMenuItem3LP.setText("Listado de Películas");
        btnMenu.add(jMenuItem3LP);

        jMenuItemIO.setText("Listado del Ingreso Obtenido");
        btnMenu.add(jMenuItemIO);

        jMenuItem5LEG.setText("Listado de Empleados Golosinas");
        btnMenu.add(jMenuItem5LEG);

        jMenuItem6MGC.setText("Listado  del Monto de Golosinas por Cliente");
        btnMenu.add(jMenuItem6MGC);

        jMenuItem7LPP.setText("Listado  de Películas Proyectadas");
        btnMenu.add(jMenuItem7LPP);

        rSMenuBar1.add(btnMenu);

        setJMenuBar(rSMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1LCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1LCFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1LCFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojeru_san.rsbutton.RSButtonForma btnAtras;
    public rojeru_san.rsbutton.RSButtonForma btnCerrarSesion;
    public rojeru_san.rsbutton.RSButtonForma btnDetalleEntr;
    public rojeru_san.rsbutton.RSButtonForma btnDetallePeli;
    public javax.swing.JMenu btnMenu;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JMenuItem jMenuItem1LCF;
    public javax.swing.JMenuItem jMenuItem2LRE;
    public javax.swing.JMenuItem jMenuItem3LP;
    public javax.swing.JMenuItem jMenuItem5LEG;
    public javax.swing.JMenuItem jMenuItem6MGC;
    public javax.swing.JMenuItem jMenuItem7LPP;
    public javax.swing.JMenuItem jMenuItemIO;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSMenuBar rSMenuBar1;
    private rojeru_san.rspanel.RSPanelGradiente rSPanelGradiente1;
    // End of variables declaration//GEN-END:variables
}
